networks:
  app:
    driver: bridge
    # external: true

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: this
      MYSQL_DATABASE: news
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - ./app_data:/var/lib/mysql 

  newsletter:
    container_name: newsletter
    build: .
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      FLASK_APP: wsgi.py        # Use wsgi.py as the app entry point
      FLASK_ENV: production      # Set the environment to production
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app   # Use gunicorn to serve the app in production

volumes:
  app_data:
