version: '3.8'
networks:
  app:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: this
      MYSQL_DATABASE: news
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    
    networks:
      - app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      [5000:5000]

# version: '3.8'

# networks:
#   app:
#     driver: bridge

# services:
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: this
#       MYSQL_DATABASE: news
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     networks:
#       - app

#   app:
#     build: .
#     volumes:
#       - .:/app
#     working_dir: /app
#     networks:
#       - app
#     depends_on:
#       - db
#     env_file:
#       - .env
#     ports:
#       - [5000:5000]
